// This file is generated by Slice Machine. Update with care!

import TestimonialsClients from './TestimonialsClients';

export {
	TestimonialsClients,
};

export const components = {
	testimonials_clients: TestimonialsClients,
};
